Add UNL CS Department
emeryberger/CSrankings pull request #1185
Opened 2018-12-04 16:23 UTC by flaviomartins

Added the entire UNL CS faculty

2018-12-04 22:03 UTC, fycus-tree commented
A lot of these URLs are broken or you're missing scholar information. 
For example, the last person is Vítor Duarte. The given URL is https://asc.di.fct.unl.pt/~vad/ but that doesn't load for me. Google gives me https://docentes.fct.unl.pt/vdt, which does load. You also say there's no scholar page, but that URL says his scholar page is https://scholar.google.pt/citations?user=Wqer7_EAAAAJ

2018-12-05 17:34 UTC, flaviomartins commented
@fycus-tree thanks for looking into this.

Unfortunately, it seems some UNL servers are down for maintenance. I've added the people and their pages as listed on https://www.di.fct.unl.pt/en/departamento/pessoas/docentes

There are two people named Vitor Duarte affiliated with the School of Science and Technology. I guess the one you found is with the Physics department. The one I'm listing is with CS.

2018-12-08 01:16 UTC, emeryberger reviewed
The current situation with the home pages is really unacceptable; I can't access most of them, and others are defective.

2018-12-08 01:16 UTC, emeryberger commented on csrankings.csv
> +Fernanda Barbosa,Universidade NOVA de Lisboa
This entry is incomplete.

2018-12-08 01:16 UTC, emeryberger commented on csrankings.csv
> +Jorge Cruz 0001,Universidade NOVA de Lisboa,https://userweb.fct.unl.pt/~jc,ENwGNokAAAAJ
It says "no permission" to access this URL. I find that I cannot access many of the listed home pages.

2018-12-08 01:16 UTC, emeryberger commented on csrankings.csv
> +José Gabriel Pereira Lopes,Universidade NOVA de Lisboa,http://dev-hlt.di.fct.unl.pt/gpl/,LRk6X3QAAAAJ
This page brings up a directory; it's not a real home page.

2018-12-18 05:39 UTC, emeryberger commented
bump, @flaviomartins

2018-12-23 22:54 UTC, flaviomartins commented
@emeryberger I have fixed all the home pages and rebased.

2018-12-25 00:53 UTC, emeryberger requested changes

2018-12-25 00:53 UTC, emeryberger commented on csrankings.csv
> +José C. Cunha,Universidade NOVA de Lisboa,http://nova-lincs.di.fct.unl.pt/person/1,VeZ4QbAAAAAJ
Per his home page, he retired a number of years ago.
http://asc.di.fct.unl.pt/~jcc/

2018-12-25 00:53 UTC, emeryberger commented on csrankings.csv
> +João Magalhães,Universidade NOVA de Lisboa,http://nova-lincs.di.fct.unl.pt/person/46,P6fBAXMAAAAJ
Please replace these generic home pages with the actual personal home pages, e.g., http://ctp.di.fct.unl.pt/~jmag/

2019-01-30 16:40 UTC, emeryberger commented
Closing for lack of response. Please feel free to reopen.

2019-01-30 16:40 UTC, closed without merging