Add three new Georgia Tech Faculty
emeryberger/CSrankings pull request #1259
Opened 2019-01-12 04:51 UTC by zsoltkira

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

2019-01-28 04:12 UTC, emeryberger requested changes

2019-01-28 04:12 UTC, emeryberger commented on csrankings.csv
> +Alexandros Daglis,Georgia Institute of Technology,https://parsa.epfl.ch/~daglis/,Mm-dHpMAAAAJ
already added.

2019-01-28 04:12 UTC, emeryberger commented on csrankings.csv
> +Matthew C. Gombolay,Georgia Institute of Technology,http://people.csail.mit.edu/gombolay/,Ihyz20wAAAAJ
Please use a GAtech website.

2019-01-29 04:25 UTC, zsoltkira commented on csrankings.csv
> +Alexandros Daglis,Georgia Institute of Technology,https://parsa.epfl.ch/~daglis/,Mm-dHpMAAAAJ
Done.

2019-01-29 04:25 UTC, zsoltkira commented on csrankings.csv
> +Matthew C. Gombolay,Georgia Institute of Technology,http://people.csail.mit.edu/gombolay/,Ihyz20wAAAAJ
Done.

2019-02-01 04:55 UTC, merged