missing scholarrank profs (250+)
emeryberger/CSrankings pull request #1269
Opened 2019-01-17 06:24 UTC by leonidk

In the same style as #1268, added faculty at existing CSRankings universities that were in scholarrank's results. Did some manual filtering to remove non-CS profs, etc. but I likely missed many of them still. There's likely some errors of the nickname variety leading to an error in DBLP affiliation but these websites all seemed accurate at the time. 

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

2019-01-22 03:44 UTC, emeryberger requested changes
This review is the result of a spot check. I found lots of issues at a glance. I think it would make a lot of sense and be a lot easier and more auditable with separate PRs for each institution.

2019-01-22 03:44 UTC, emeryberger commented on csrankings.csv
> +James Tompkin,Brown University,https://cs.brown.edu/courses/csci1430/,Ex3pgLAAAAAJ
Correct home page should be: http://jamestompkin.com/

2019-01-22 03:44 UTC, emeryberger commented on csrankings.csv
> +Angelos D. Keromytis,Columbia University,http://www.cs.columbia.edu/~angelos/,mncyWbcAAAAJ
In fact, he's at GAtech now (left DARPA). https://www.ece.gatech.edu/faculty-staff-directory/angelos-d-keromytis

2019-01-22 03:44 UTC, emeryberger commented on csrankings.csv
> +Rong Ge,Duke University,https://users.cs.duke.edu/~rongge/,MVxcjEoAAAAJ
Already in the database as:
* Rong Ge 0001,Duke University,https://users.cs.duke.edu/~rongge,MVxcjEoAAAAJ

2019-01-22 03:44 UTC, emeryberger commented on csrankings.csv
> +Landon P. Cox,Duke University,https://users.cs.duke.edu/~lpcox/,zoBGvW4AAAAJ
Landon left Duke (permanently) for MSR.

2019-01-22 03:44 UTC, emeryberger commented on csrankings.csv
> +Frank Dellaert,Georgia Institute of Technology,https://www.cc.gatech.edu/people/frank-dellaert,ZxXBaswAAAAJ
Correct home page:
* https://www.cc.gatech.edu/~dellaert/FrankDellaert/Frank_Dellaert/Frank_Dellaert.html

2019-01-22 03:54 UTC, leonidk commented
Yeah, I'd like to do a manual audit of this list if I get some extra time (the names from the dataset were often bad/misspelled/missing middle names, and certainly had no DBLP disambiguation). I used some fuzzy string matching to get DBLP names and a scraper to get websites. But I figured I'd open a pull request so (at least) this initial set is available to people. The names were ordered by university to make auditing easier but ultimately it'll just require a chunk of time from someone, and I'm not sure when & if that someone could be me. 

I think reaching out to [these authors](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0202223) for the guids <-> names in their [dataset](https://github.com/allisonmorgan/academic_census) might be useful.

2019-02-05 16:41 UTC, emeryberger commented
I don't have the time to personally audit this. Can you resolve the changes I mentioned and then break this up into commits per school so I (and others) can review these? Otherwise, I will have to close this. Thanks.

2019-02-25 05:36 UTC, emeryberger commented
bump @leonidk . I hate to discard all these but I cannot manually audit such a large commit.

2019-03-26 03:50 UTC, emeryberger commented
Closing for lack of response.

2019-03-26 03:50 UTC, closed without merging