Add CS faculty members in Shenzhen University
emeryberger/CSrankings pull request #1275
Opened 2019-01-21 14:54 UTC by jihuomail

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x]  Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x]  Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x]  If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x]  Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x]  If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x]  If the institution you are adding is not in the US,
update `country-info.csv`.

2019-01-27 01:00 UTC, emeryberger commented
There are numerous DBLP entries in lieu of home pages. These all need to point to actual faculty home pages. There is also a conflict in `country-info.csv` that needs to be resolved.

2019-01-28 04:37 UTC, emeryberger requested changes

2019-01-28 04:37 UTC, emeryberger commented on csrankings.csv
> +Daming Shi 0001,Shenzhen University,https://dblp.uni-trier.de/pers/s/Shi_0001:Daming,8nZ0ukUAAAAJ
DBLP is not a home page.

2019-01-28 04:37 UTC, emeryberger commented on csrankings.csv
> +Dingming Wu,Shenzhen University,https://dblp.uni-trier.de/search?q=Dingming+Wu,oRbQlsEAAAAJ
DBLP is not a home page.

2019-01-28 04:37 UTC, emeryberger commented on csrankings.csv
> +Hao Liao,Shenzhen University,https://dblp.org/pers/hd/l/Liao:Hao,Tu5ZuREAAAAJ
As above, DBLP is not a valid home page.

2019-02-09 00:59 UTC, emeryberger commented
bump @jihuomail

2019-02-15 09:09 UTC, jihuomail commented
@emeryberger Thanks for your comments.

I have removed those faculties from the list who do not have their own personal homepage, and replaced some dblp pages as mentioned. Could you please help check again?

2019-02-16 16:57 UTC, emeryberger commented
You apparently edited the file with Excel. That does not work; it corrupts many Google Scholar entries. Please edit with something else.

2019-02-18 03:59 UTC, emeryberger approved these changes

2019-02-18 03:59 UTC, emeryberger commented
Thanks; please resolve conflicts and I will merge.

2019-02-18 04:17 UTC, jihuomail commented
Hi @emeryberger I can not see any conflicts currently, how can I resolve the conflicts?

2019-02-19 05:53 UTC, emeryberger commented
Do a pull and you will see them.

2019-02-19 09:51 UTC, jihuomail commented
Hi @emeryberger Could you please help me resolve the conflicts (merge my branch with commit f9abefa)? I tried to follow your suggestions and found the conflicts in my local repository, after updating, it seemed that I made it worse...

2019-02-20 00:14 UTC, emeryberger commented
How about you close this PR and open a new one, forking the most recent repo?

2019-02-20 01:59 UTC, jihuomail commented
Thanks! I will do it.

2019-02-20 01:59 UTC, closed without merging