Updated UVA Faculty
emeryberger/CSrankings pull request #1290
Opened 2019-01-29 17:25 UTC by westre3

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

2019-01-30 16:55 UTC, emeryberger requested changes

2019-01-30 16:55 UTC, emeryberger commented on csrankings.csv
> -Aaron Bloomfield,University of Virginia,https://engineering.virginia.edu/faculty/aaron-bloomfield,NOSCHOLARPAGE
Please explain / justify this removal. He still appears here: https://engineering.virginia.edu/departments/computer-science/faculty.

2019-01-30 16:55 UTC, emeryberger commented on csrankings.csv
> +Christopher Barrett,University of Virginia,https://engineering.virginia.edu/faculty/christopher-l-barrett/NOSCHOLARPAGE
Ill-formed -- you need a comma before NOSCHOLARPAGE.

2019-01-30 16:55 UTC, emeryberger commented on csrankings.csv
> +Matthew Dwyer,University of Virginia,http://matthewbdwyer.github.io/ZRKCcEAAAAJ&hl
Ill-formed; need a comma after the home page.

2019-01-30 16:55 UTC, emeryberger commented on csrankings.csv
> +Matthew Dwyer,University of Virginia,http://matthewbdwyer.github.io/ZRKCcEAAAAJ&hl
This is also not the correct DBLP name: https://dblp.uni-trier.de/pers/hd/d/Dwyer:Matthew_B=

PLEASE check all the boxes in the commit contribution guidelines (and do what it says).

2019-01-30 16:55 UTC, emeryberger commented on csrankings.csv
> +Sebastian Elbaum,University of Virginia,https://engineering.virginia.edu/faculty/sebastian-elbaum/swPW5FYAAAAJ
Another ill-formed entry.

2019-02-05 17:56 UTC, westre3 commented
* Aaron Bloomfield was removed because he is not tenured/tenure-track. Currently, the web page you linked to does not differentiate between non-tenure-track, teaching-track faculty and tenured/tenure-track faculty.

* The entry for Matthew Dwyer that was ill-formed has been removed because it had been accidentally added as a duplicate.

* The other ill-formed entries have been corrected.

2019-02-05 18:28 UTC, emeryberger approved these changes

2019-02-05 18:29 UTC, merged

2019-02-05 18:29 UTC, emeryberger commented
Thanks!