Lower page threshold for FOCS, STOC, and SODA
emeryberger/CSrankings pull request #1327
Opened 2019-02-10 18:28 UTC by zlangley

Papers with 4-5 pages are not too uncommon in these conferences, and it
seems useful to have knobs for this filter per-conference, rather than
globally.

Also use an OrderedDict for articles.json writing to ensure that the ordering
does not change across Python versions.

2019-02-10 19:35 UTC, emeryberger requested changes

2019-02-10 19:35 UTC, emeryberger commented on util/csrankings.py
> +    'FOCS': 4,
I am not going to adopt these changes as part of this PR. Please delete the dict entries.

2019-02-10 19:36 UTC, emeryberger commented
Lowering the page threshold for a conference is a policy decision and is inappropriate as a PR.

2019-02-10 20:09 UTC, zlangley commented
It seems that many legitimate papers are being filtered out by the current criteria—I have personally noticed a few theory papers missing—and a PR seemed a perfectly natural way to open the discussion with a proposed solution.

2019-02-10 20:09 UTC, closed without merging

2019-02-11 00:23 UTC, emeryberger commented
It's fine as an issue. But the paper threshold is uniform across all areas of CS, and it would be highly unusual to suddenly lift it for one community; I also think it would be buried as a PR.