Updates for UNIST CSE
emeryberger/CSrankings pull request #1354
Opened 2019-02-19 11:53 UTC by hyungon-moon

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

2019-02-20 00:13 UTC, emeryberger requested changes

2019-02-20 00:13 UTC, emeryberger commented on csrankings.csv
> +Kwang In Kim,UNIST,,0wIdMGEAAAAJ
Needs a home page URL.

2019-02-20 00:13 UTC, emeryberger commented on csrankings.csv
> -Aaram Yun,UNIST,http://aaramyun.unist.ac.kr,NOSCHOLARPAGE
Please explain removal. This person appears to still be there...

2019-02-21 13:40 UTC, closed without merging

2019-02-21 13:40 UTC, hyungon-moon commented
Will make another one with some fixes.