csranking: kui ren, wenbo shen, jinsong han, Zhejiang University. dbl…
emeryberger/CSrankings pull request #1386
Opened 2019-03-06 12:39 UTC by Jeimon

…p: kui ren and kui ren 0001

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

2019-03-06 15:09 UTC, Jeimon commented
#

2019-03-07 18:51 UTC, emeryberger requested changes

2019-03-07 18:51 UTC, emeryberger commented on dblp-aliases.csv
> +Kui Ren,Kui Ren 0001
Please delete this. The main entry should be the DBLP entry (that is, Kui Ren 0001).

2019-03-07 18:51 UTC, emeryberger commented on csrankings.csv
> +Kui Ren,Zhejiang University,https://person.zju.edu.cn/kuiren,uuQA_rcAAAAJ
Use the DBLP name (Kui Ren 0001).

2019-03-26 03:50 UTC, emeryberger commented
Closing for lack of response in > 2 weeks.

2019-03-26 03:50 UTC, closed without merging