add Marshini Chetty at University of Chicago
emeryberger/CSrankings pull request #1526
Opened 2019-05-23 19:42 UTC by feamster

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

2019-05-27 22:43 UTC, emeryberger requested changes

2019-05-27 22:43 UTC, emeryberger commented on csrankings.csv
> +Samory Kpotufe,Columbia University,http://www.columbia.edu/~skk2175,NOSCHOLARPAGE
In Stats dept., not CS.

2019-05-28 01:23 UTC, feamster commented
Done.

2019-05-28 01:24 UTC, feamster commented on csrankings.csv
> +Samory Kpotufe,Columbia University,http://www.columbia.edu/~skk2175,NOSCHOLARPAGE
Fixed.

2019-05-28 01:29 UTC, merged

2019-05-28 01:29 UTC, emeryberger commented
thanks!

2019-05-28 01:32 UTC, feamster commented
Sure thing!

-Nick

On May 27, 2019 9:29:25 PM EDT, Emery Berger <notifications@github.com> wrote:
>thanks!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/emeryberger/CSrankings/pull/1526#issuecomment-496332921