Added a faculty member at KAIST
emeryberger/CSrankings pull request #2797
Opened 2020-07-15 23:56 UTC by aailabkaist

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [ O ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [O] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [O] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ O] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [O ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ O] If the institution you are adding is not in the US,
update `country-info.csv`.

2020-07-16 15:56 UTC, emeryberger requested changes

2020-07-16 15:56 UTC, emeryberger commented on csrankings.csv
> +Il-Chul Moon,KAIST,http://aai.kaist.ac.kr,23AxIc0AAAAJ
Not in CS; please explain how this meets the inclusion criteria.

2020-07-20 16:15 UTC, emeryberger commented
Bump @aailabkaist

2020-07-21 01:12 UTC, aailabkaist commented
I did not pay attention to this part. "who can solely advise PhD students in Computer Science."

I am closing the pull request. Thanks

2020-07-21 01:12 UTC, closed without merging