Restoring Sapienza faculty apparently not included in latest merge
emeryberger/CSrankings pull request #2853
Opened 2020-08-03 09:01 UTC by cdc08x

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

2020-08-21 00:24 UTC, emeryberger commented on csrankings.csv
> +Roberto Beraldi,Sapienza University of Rome,http://www.diag.uniroma1.it/users/roberto%20beraldi,WaJQ4-wAAAAJ
Please remove the incorrect entry (not sure which).

2020-08-21 00:25 UTC, emeryberger requested changes
Please remove spurious duplicate.

2020-08-22 12:46 UTC, cdc08x commented
Hi!

I am not sure if that is the issue but if this is the one:
`Roberto Baldoni,Sapienza University of Rome,http://www.diag.uniroma1.it/users/roberto%20baldoni,82tR6VoAAAAJ
Roberto Beraldi,Sapienza University of Rome,http://www.diag.uniroma1.it/users/roberto%20beraldi,WaJQ4-wAAAAJ`
actually,
Roberto Ba_ldoni_
and
Roberto Be_raldi_
are two different people. Is it OK as a clarification?

Thanks a lot for your great, admirable work!

Cheers

2020-08-22 14:13 UTC, emeryberger commented
Sigh, somehow I saw those as the same - sorry! Thanks!

2020-08-22 14:13 UTC, emeryberger approved these changes

2020-08-22 14:14 UTC, merged

2020-08-23 19:34 UTC, cdc08x commented
Never mind! No problem at all. Thanks a lot for your help!