Update csrankings.csv
emeryberger/CSrankings pull request #2899
Opened 2020-08-25 00:44 UTC by collider123

add some Cleveland State University faculty

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

2020-10-11 20:56 UTC, emeryberger commented
1. Please remove spaces after commas in every entry.
2. Please add _every_ tenure-track faculty member listed here: https://engineering.csuohio.edu/eecs/electrical-computer-engineering-faculty

> If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

2020-10-18 16:20 UTC, collider123 commented
All CS tenure-track faculty listed here https://engineering.csuohio.edu/eecs/computer-science-faculty and here https://engineering.csuohio.edu/eecs/electrical-computer-engineering-faculty have been added.

Thanks.

2020-10-31 00:54 UTC, emeryberger requested changes

2020-10-31 00:54 UTC, emeryberger commented on csrankings.csv
> +Chansu Yu,https://academic.csuohio.edu/yuc/,NOSCHOLARPAGE
Missing affiliation

2020-10-31 01:03 UTC, collider123 commented on csrankings.csv
> +Chansu Yu,https://academic.csuohio.edu/yuc/,NOSCHOLARPAGE
missing affiliation added. Thank you

2020-10-31 02:10 UTC, merged