Update csrankings-5.csv
emeryberger/CSrankings pull request #3268
Opened 2021-01-26 13:37 UTC by ad1tyawagh

Marc Toussaint has moved to TU Berlin from University of Stuttgart.

2021-01-26 13:48 UTC, ad1tyawagh commented
Kostas Alexis has moved to NTNU from University of Nevada, Reno.  The commit  `e0588d2` represents that change.

2021-03-12 15:58 UTC, emeryberger commented on csrankings-4.csv
> +Kostas Alexis,NTNU,http://www.kostasalexis.com/
Missing Google Scholar link.

2021-03-12 15:59 UTC, emeryberger requested changes

2021-03-12 15:59 UTC, emeryberger commented on csrankings-5.csv
> +Marc Toussaint,TU Berlin,https://www.user.tu-berlin.de/mtoussai/index.html
Missing Google Scholar link.

2021-03-12 16:12 UTC, ad1tyawagh commented on csrankings-5.csv
> +Marc Toussaint,TU Berlin,https://www.user.tu-berlin.de/mtoussai/index.html
Missed it! Updating ASAP.

2021-03-12 16:12 UTC, ad1tyawagh commented on csrankings-4.csv
> +Kostas Alexis,NTNU,http://www.kostasalexis.com/
Missed it! Updating ASAP.

2021-03-12 16:22 UTC, merged