Updating GMU CS faculty
emeryberger/CSrankings pull request #3705
Opened 2021-07-24 03:16 UTC by nguyenthanhvuh

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

0. Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv"). **IF YOU DO NOT DO THIS, YOUR COMMIT WILL BE SUMMARILY REJECTED.**

1. _Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

2. _Insert new faculty **in alphabetical order**, not at the end of `csrankings-[a-z].csv`._ **Do not modify `csrankings.csv`, which is auto-generated.** **DO NOT MODIFY `csrankings-[0-9].csv`, WHICH ARE BEING DEPRECATED. USE `csrankings-[a-z].csv` INSTEAD.**

3. _Read and check **all** the boxes below by filling them in with an X._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

**(Advanced) Quick contribution via a shallow clone** 

A full clone of the CSrankings repository is almost 2GB.  To contribute a change without creating a full local clone of the CSrankings repo, you can do a _shallow clone_.  To do so, follow these steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)
2. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.
3. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to do another contribution and some time has passed, perform steps 1-3 again, creating a fresh fork and shallow clone.

2021-07-24 16:46 UTC, nguyenthanhvuh commented
List of faculty at GMU: https://cs.gmu.edu/directory/by-category/faculty/

2021-09-04 20:21 UTC, emeryberger requested changes

2021-09-04 20:21 UTC, emeryberger commented on csrankings-e.csv
> +Evgenios Kornaropoulos,George Mason University,https://evgeniosk.github.io,2s0r_AkAAAAJ
Web page doesn't work.

2021-09-04 20:21 UTC, emeryberger commented on csrankings-g.csv
> +Giuseppe Ateniese,George Mason University,https://ateniese.github.io,EyZJ08MAAAAJ
Web page still says Stevens. Please point to something indicating new affiliation.

2021-09-04 20:21 UTC, emeryberger commented on csrankings-j.csv
> +Jonathan Warrell,George Mason University,https://sites.google.com/site/jonathanwarrell,3KHjDQ4AAAAJ
No indication of GMU affiliation on web page.

2021-09-04 20:21 UTC, emeryberger commented on csrankings-x.csv
> +Xiaokuan Zhang,George Mason University,http://web.cse.ohio-state.edu/~zhang.5840/,HbuPL5IAAAAJ
No indication of GMU affiliation on home page.

2021-09-04 20:21 UTC, emeryberger commented on csrankings-x.csv
> +Xuesu Xiao,George Mason University,https://www.cs.utexas.edu/~xiao/,bWbsbjAAAAAJ
Not joining until Fall 2022; please submit a PR in January.

2021-09-04 20:59 UTC, nguyenthanhvuh commented
@emeryberger thanks,  all mentioned problems should be fixed now.  Most of those who don't mention GMU are those joining next year and so I just remove them in this PR as you said.

2021-09-05 07:31 UTC, emeryberger approved these changes

2021-09-05 07:32 UTC, merged