Added University of Klagenfurt
emeryberger/CSrankings pull request #4011
Opened 2021-09-10 16:44 UTC by juliusKoepke

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

0. Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv"). **IF YOU DO NOT DO THIS, YOUR COMMIT WILL BE SUMMARILY REJECTED.**

1. _Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

2. _Insert new faculty **in alphabetical order**, not at the end of `csrankings-[a-z].csv`._ **Do not modify `csrankings.csv`, which is auto-generated.** **DO NOT MODIFY `csrankings-[0-9].csv`, WHICH ARE BEING DEPRECATED. USE `csrankings-[a-z].csv` INSTEAD.**

3. _Read and check **all** the boxes below by filling them in with an X._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

**(Advanced) Quick contribution via a shallow clone** 

A full clone of the CSrankings repository is almost 2GB.  To contribute a change without creating a full local clone of the CSrankings repo, you can do a _shallow clone_.  To do so, follow these steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)
2. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.
3. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to do another contribution and some time has passed, perform steps 1-3 again, creating a fresh fork and shallow clone.

2021-10-14 19:55 UTC, emeryberger requested changes

2021-10-14 19:55 UTC, emeryberger commented on csrankings-a.csv
> +Angelika Wiegele,University of Klagenfurt,https://www.aau.at/mathematik,2llVxoYAAAAJ
Not a home page; also please explain how this person meets inclusion criteria (if in Math rather than Computer Science / Informatik).

2021-10-14 19:55 UTC, emeryberger commented on csrankings-b.csv
> +Barbara Kaltenbacher,University of Klagenfurt,https://www.aau.at/mathematik,o6qc9IoAAAAJ
Not an  actual home page, see above comment.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-b.csv
> +Barbara Kaltenbacher,University of Klagenfurt,https://www.aau.at/mathematik,o6qc9IoAAAAJ
(Must be able to *solely* advise a PhD student for a degree in *Computer Science* (or local equivalent).

2021-10-14 19:55 UTC, emeryberger commented on csrankings-c.csv
> +Christian Pötzsche,University of Klagenfurt,https://www.aau.at/mathematik,NOSCHOLARPAGE
Same comment as previous cases in Math.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-c.csv
> +Clemens Heuberger,University of Klagenfurt,https://www.aau.at/mathematik,NOSCHOLARPAGE
As above.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-e.csv
> +Elena Resmerita,University of Klagenfurt,https://www.aau.at/mathematik,HXJV5jgAAAAJ
Same issue.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-f.csv
> +Franz Rendl,University of Klagenfurt,https://www.aau.at/mathematik,6i8tJAgAAAAJ
Same issue.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-f.csv
> +Friederike Wall,University of Klagenfurt,https://www.aau.at/unternehmensfuehrung/controlling-und-strategische-unternehmensfuehrung/team/wall-friederike,fLXVWaQAAAAJ
Looks like Operations Research and not Computer Science; please clarify with respect to inclusion eligibility criteria.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-k.csv
> +Katharina Kinder-Kurlanda,University of Klagenfurt,https://katharinakinderkurlanda.net,VVms_qoAAAAJ
Cultural anthropologist; not clear how meets eligibility criteria.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-s.csv
> +Stephan Leitner,University of Klagenfurt,https://www.aau.at/unternehmensfuehrung/controlling-und-strategische-unternehmensfuehrung/team/leitner-stephan,L5FT_2gAAAAJ
Not clearly in CS.

2021-10-14 19:55 UTC, emeryberger commented on csrankings-w.csv
> +Winfried B. Müller,University of Klagenfurt,https://www.aau.at/mathematik,NOSCHOLARPAGE
Same problem as many.

2021-10-18 09:03 UTC, juliusKoepke commented
Updated Pull request removed colleagues from math departement.

2021-10-19 13:40 UTC, emeryberger commented on csrankings-c.csv
> +Clemens Heuberger,University of Klagenfurt,https://www.aau.at/mathematik,NOSCHOLARPAGE
Please remove this person and I can merge this PR.

2021-10-19 13:45 UTC, juliusKoepke commented on csrankings-c.csv
> +Clemens Heuberger,University of Klagenfurt,https://www.aau.at/mathematik,NOSCHOLARPAGE
done

2021-10-20 14:19 UTC, merged