Update homepages for C. Dunne, M. Borkin. New affiliation for E. Bertini. New entry for M. Tory.
emeryberger/CSrankings pull request #4076
Opened 2021-09-28 15:39 UTC by codydunne

* Update homepage for Cody Dunne
* Update homepage for Michelle Borkin
* Update affiliation, homepage, Google Scholar disambiguation for Enrico Bertini (new hire at Northeastern, starting January 2022)
* Add new faculty Melanie Tory (new hire at Northeastern)

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

0. Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv"). **IF YOU DO NOT DO THIS, YOUR COMMIT WILL BE SUMMARILY REJECTED.**

1. _Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

2. _Insert new faculty **in alphabetical order**, not at the end of `csrankings-[a-z].csv`._ **Do not modify `csrankings.csv`, which is auto-generated.** **DO NOT MODIFY `csrankings-[0-9].csv`, WHICH ARE BEING DEPRECATED. USE `csrankings-[a-z].csv` INSTEAD.**

3. _Read and check **all** the boxes below by filling them in with an X._

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

**(Advanced) Quick contribution via a shallow clone** 

A full clone of the CSrankings repository is almost 2GB.  To contribute a change without creating a full local clone of the CSrankings repo, you can do a _shallow clone_.  To do so, follow these steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)
2. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.
3. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to do another contribution and some time has passed, perform steps 1-3 again, creating a fresh fork and shallow clone.

2021-10-28 01:02 UTC, emeryberger requested changes

2021-10-28 01:02 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Not in CS; please point to cross-affiliation or other indication they can solely advise students in CS.

2021-10-28 01:02 UTC, emeryberger commented on csrankings-e.csv
> +Enrico Bertini,Northeastern University,http://enrico.bertini.io/,_jGHG0IAAAAJ
Please point to a page indicating the change of affiliation.

2021-10-28 15:37 UTC, codydunne commented on csrankings-e.csv
> +Enrico Bertini,Northeastern University,http://enrico.bertini.io/,_jGHG0IAAAAJ
Please see our "Khoury welcomes new faculty" announcement:
https://www.khoury.northeastern.edu/khoury-welcomes-new-faculty-for-2021-22/#bertini
His bio page for the college:
https://www.khoury.northeastern.edu/people/enrico-bertini/
Enrico's Tweet about the move:
https://mobile.twitter.com/FILWD/status/1451219788462702594

2021-10-28 15:38 UTC, codydunne commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Please see our "Khoury welcomes new faculty" announcement:
https://www.khoury.northeastern.edu/khoury-welcomes-new-faculty-for-2021-22/#tory

2021-11-03 17:11 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Is this faculty member at the institute in Maine? Such faculty members are not eligible for inclusion.

2021-11-03 17:34 UTC, codydunne commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Yes, she is part of the [Roux Institute at Northeastern University](https://roux.northeastern.edu/). But it really is a part of the same university. She has an appointment in our College, attends the same faculty meetings, works with the same College and University staff that I do inc. for grant writing and human-subjects research, travels between the campuses frequently... At Northeastern, students can also often take classes taught by faculty who sit at other campuses. 

What is the criteria here? If not Northeastern University, which institution should she be listed under?

2021-11-03 18:23 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Each institution listed must logically be the same institution in every regard: they must, for example, have a unified grad student admission process, where every grad student may choose to attend the campus/institute of their choice; the hiring process must be unified, etc.

2021-11-03 18:24 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
It's not about the university per se, but rather the computer science department/school.

2021-11-03 18:25 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
There is a very high bar for inclusion of physically distributed campuses. There are very very few instances in the database right now.

2021-11-03 18:28 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
I recommend you remove this faculty member at this time and we can discuss this later off-line.

2021-11-06 15:34 UTC, emeryberger commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Bump @codydunne

2021-11-10 18:10 UTC, codydunne commented on csrankings-m.csv
> +Melanie Tory,Northeastern University,https://www.melanietory.com/,cKMhiMkAAAAJ
Sorry for the delay! Done @emeryberger. Sure, lets chat offline.

2021-11-11 22:07 UTC, merged