add several recent[ish] UBC faculty
emeryberger/CSrankings pull request #4089
Opened 2021-10-04 07:04 UTC by djsutherland

Adds some 2021 arrivals to UBC.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.   [not relevant]

- [x] If the institution you are adding is not in the US, update `country-info.csv`.   [not relevant]

2021-10-28 01:26 UTC, emeryberger requested changes

2021-10-28 01:26 UTC, emeryberger commented on csrankings-j.csv
> +Jeff Clune,University of British Columbia,https://www.cs.ubc.ca/people/jeff-clune,5TZ7f5wAAAAJ
Please clarify if this person's position is >75% at UBC (vs. OpenAI).

2021-10-29 06:33 UTC, djsutherland commented on csrankings-j.csv
> +Jeff Clune,University of British Columbia,https://www.cs.ubc.ca/people/jeff-clune,5TZ7f5wAAAAJ
I'm pretty sure yes, but @jeffclune can confirm.

2021-10-29 15:06 UTC, jeffclune commented on csrankings-j.csv
> +Jeff Clune,University of British Columbia,https://www.cs.ubc.ca/people/jeff-clune,5TZ7f5wAAAAJ
Yes. I confirm I meet that threshold. Thanks!

2021-10-29 20:26 UTC, djsutherland commented
(Rebased to resolve a merge conflict that happened in the meantime.)

2021-11-03 16:45 UTC, merged