Added ShanghaiTech University Faculty
emeryberger/CSrankings pull request #4171
Opened 2021-10-30 19:22 UTC by Dzhange

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

0. Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv"). **IF YOU DO NOT DO THIS, YOUR COMMIT WILL BE SUMMARILY REJECTED.**

1. _Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

2. _Insert new faculty **in alphabetical order**, not at the end of `csrankings-[a-z].csv`._ **Do not modify `csrankings.csv`, which is auto-generated.** **DO NOT MODIFY `csrankings-[0-9].csv`, WHICH ARE BEING DEPRECATED. USE `csrankings-[a-z].csv` INSTEAD.**

3. _Read and check **all** the boxes below by filling them in with an X._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

**(Advanced) Quick contribution via a shallow clone** 

A full clone of the CSrankings repository is almost 2GB.  To contribute a change without creating a full local clone of the CSrankings repo, you can do a _shallow clone_.  To do so, follow these steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)
2. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.
3. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to do another contribution and some time has passed, perform steps 1-3 again, creating a fresh fork and shallow clone.

2021-11-06 16:13 UTC, emeryberger requested changes

2021-11-06 16:13 UTC, emeryberger commented on csrankings-f.csv
> +Fu Song, ShanghaiTech University,https://sist.shanghaitech.edu.cn/sist_en/2020/0814/c7582a54913/page.htm,RTTSafIAAAAJ
Remove spurious space after comma.

2021-11-06 16:13 UTC, emeryberger commented on csrankings-j.csv
> +Jingya Wang, ShanghaiTech University,https://sist.shanghaitech.edu.cn/2020/0707/c7499a58578/page.htm,vmvJV_IAAAAJ
Remove spurious space after comma.

2021-11-06 16:13 UTC, emeryberger commented on csrankings-s.csv
> +Shenghua Gao,ShanghaiTech University, https://svip-lab.github.io/news.html,fe-1v0MAAAAJ
Remove spurious space after comma.

2021-11-07 15:48 UTC, Dzhange commented
Removed spurious space and resolved conflicts, please check, thanks

2021-11-07 17:41 UTC, emeryberger commented
Please re-pull a, c, and d, which are all conflicting (presumably because of line ending issues).

2021-11-08 03:32 UTC, Dzhange commented
Thanks for the instruction. I just pulled, does it work now?

2021-11-08 03:32 UTC, emeryberger commented
I still see a, c, and d with huge diffs.

2021-11-08 03:34 UTC, Dzhange commented
sorry let me try it again

2021-11-08 03:51 UTC, Dzhange commented
I just downloaded the a,c,d files directly from the original repo and committed again, but there still is huge diff, kind of weird

2021-11-08 03:54 UTC, Dzhange commented
And when I try to pull from the upstream it says "Already up to date"

2021-11-08 05:09 UTC, emeryberger commented
how about you just remove the a,c,d files from this PR so I can merge it, and you can open another PR?

2021-11-08 05:13 UTC, Dzhange commented
Yeah let me try that

2021-11-08 05:19 UTC, emeryberger commented
Unfortunately, this merge would *delete* the above-mentioned files :(

2021-11-08 05:21 UTC, Dzhange commented
Oh no, does that mean it would delete those files in the origin repo?

2021-11-08 05:32 UTC, Dzhange commented
Another solution is I just close this pull request and redo all the editing, should take less time than figuring out this mystery

2021-11-08 05:48 UTC, emeryberger commented
Yeah, agreed, let's close it and start over

2021-11-08 05:48 UTC, closed without merging