Add profile for Dr. Timothy O'Donnell
emeryberger/CSrankings pull request #4719
Opened 2022-06-08 18:24 UTC by xhlulu

Dr. Timothy J. O'Donnell is a full-time Assistant Professor at McGIll University. He is affiliated with the Department of Linguistics. However, he is active in the NLP area of research, having published over 6 papers in [NLP conferences like ACL/EMNLP](https://aclanthology.org/people/t/timothy-odonnell/) and also [NeurIPS](https://proceedings.neurips.cc/paper/2021/file/0a4dc6dae338c9cb08947c07581f77a2-Paper.pdf).

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

2022-08-06 16:00 UTC, emeryberger requested changes

2022-08-06 16:00 UTC, emeryberger commented on csrankings-t.csv
> +Timothy J. O'Donnell,McGill University,https://mcqll.org/people/odonnell.timothy/,iYjXhYwAAAAJ
No evidence that they meet inclusion criteria (must be in CS or with affiliate appointment, for example).

2022-08-08 15:48 UTC, xhluca commented
@emeryberger Dr. O'Donnell is an associate member of the school of computer science at McGill (see "Associate Members" section): https://cs.mcgill.ca/people/faculty/

Is that what you meant by affiliate appointment?

2022-08-08 15:56 UTC, emeryberger commented
You need to remove `dblp-aliases.csv` from this PR - it is now automatically generated. (Do _not_ `git rm` it,  because that will remove it from the main repo on merge.)

2022-08-08 16:34 UTC, xhluca commented
@emeryberger Thanks for automating dblp-aliases. I have removed the change I have made.

2022-08-08 16:37 UTC, merged