Update UoUtah
emeryberger/CSrankings pull request #7035
Opened 2024-03-21 19:29 UTC by jay-tau

# Contributing to CSrankings

Thanks for contributing to CSrankings! Please read and indicate you agree with **all** these guidelines to getting your pull request accepted. Note that pull requests may take some time to get merged (please don't contact us for at least three months for updates, unless you are a sponsor - see below).

**If you find CSrankings useful, [please consider becoming a sponsor](https://github.com/sponsors/csrankings).**

**NOTE:** IF YOU DO NOT FOLLOW THE STEPS BELOW, YOUR PULL REQUEST WILL BE SUMMARILY REJECTED.
You must read and check **all** the boxes below by filling them in with an X or your PR will be rejected.

**The Basics**

- [ ] All pull requests and issues must come from non-anonymous accounts. Make sure your GitHub profile contains your full name.

- [ ] Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv").

- [ ] Combine multiple updates to a single institution into a **single PR.**

- [ ] Only submit one pull request per institution.

- [ ] Do not modify any files except `csrankings-[a-z].csv` or (if needed) `country-info.csv` and `old/industry.csv` (see below).

- [ ] Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use the GitHub user interface or a text editor like emacs or NotePad instead.

- [ ] Insert new faculty **in alphabetical order** (not at the end) in the appropriate `csrankings-[a-z].csv` files. **Do not modify `csrankings.csv`, which is auto-generated.**

- [ ] Check to make sure that you have no spaces after commas, or any missing fields.

- [ ] Check to make sure the home page is correct.

- [ ] Make sure the Google Scholar IDs are just the alphanumeric identifier (not a URL or with `&hl=en`).

- [ ] Check to make sure the name corresponds to the DBLP entry (look it up at http://dblp.org).

- [ ] If a faculty member is not in a CS department or similar, include a comment explaining how they meet the inclusion criteria (see below).

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. **Provide justification, pointing to specific home pages
showing how faculty not in a CS department meet the inclusion criteria,
e.g. showing a courtesy appointment in CS.** Faculty must also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put `NOSCHOLARPAGE`.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire CS faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**); include disambiguation suffixes like `0001` as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, *all of them need to be listed*. Do not update `dblp-aliases.csv`.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv` and add *all* of the faculty in the CS department.

**(Advanced) Quick contribution via a shallow clone** 

We recommend that you use the GitHub web user interface to make changes. However, it may be more convenient
to clone the repository for larger-scale changes.

However, a full clone of the CSrankings repository is almost 2GB.  To
contribute a change without creating a full local clone of the
CSrankings repo, you can perform a _shallow clone_.  To do so, follow these
steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)

1. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.

1. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to make another contribution and some time has passed, perform these steps again, creating a fresh fork and shallow clone.

2024-05-20 09:21 UTC, jay-tau commented on csrankings-l.csv
> +Luis Antonio Garcia,University of Utah,https://lagarcia.us,F6Gzg9gAAAAJ
This is being flagged as a disambiguation entry.
However, this is an alias for Luis Garcia 0001 (https://dblp.org/pid/67/136-1.html)

2024-05-26 18:27 UTC, emeryberger requested changes

2024-05-26 18:27 UTC, emeryberger commented on csrankings-e.csv
> +Eric Eide,University of Utah,https://users.cs.utah.edu/~eeide,b00P0C8AAAAJ
Research faculty, not eligible for inclusion (sorry, Eric)

2024-05-26 18:27 UTC, emeryberger commented on csrankings-e.csv
> +Eric Norman Eide,University of Utah,https://users.cs.utah.edu/~eeide,b00P0C8AAAAJ
See above

2024-05-26 18:27 UTC, emeryberger commented on csrankings-f.csv
> +Fengguang Song,IUPUI,http://cs.iupui.edu/~fgsong,BoVnm1wAAAAJ
Please remove this entry

2024-05-26 18:27 UTC, emeryberger commented on csrankings-r.csv
> +Robert Ricci,University of Utah,https://ricci.io,zHHD40YAAAAJ
Research faculty, not eligible for inclusion. Please remove

2024-06-19 14:19 UTC, emeryberger requested changes
All faculty given here who have "Lecturer" by their name are not TT faculty and need to be removed. https://www.cs.utah.edu/people/faculty/

2024-06-19 14:19 UTC, emeryberger commented on csrankings-e.csv
> +Eric Heisler,University of Utah,https://ericheisler.github.io,FUxJhrIAAAAJ
Not TT faculty; remove.

2024-06-19 14:19 UTC, emeryberger commented on csrankings-d.csv
> +David E. Johnson 0001,University of Utah,https://users.cs.utah.edu/~dejohnso/index.shtml,HZv4Np8AAAAJ
Not TT faculty; remove.

2024-06-19 14:19 UTC, emeryberger commented on csrankings-b.csv
> +Ben Jones,University of Utah,https://users.cs.utah.edu/~benjones,NOSCHOLARPAGE
Not TT faculty; remove.

2024-06-19 15:15 UTC, jay-tau commented
Fixed @emeryberger 
Is there any resource that lists the various types of non-tenure type faculty? Different universities seem to follow different naming conventions, making it rather confusing :/

2024-06-19 18:12 UTC, emeryberger commented
"Lecturer" in US institutions is a strong indicator of non-TT (as is "Research" by a title, anywhere).

2024-06-19 18:12 UTC, merged