UpdateEntryViscontifromUNISAtoSapienza-csrankings-i.csv
emeryberger/CSrankings pull request #7650
Opened 2024-09-14 18:46 UTC by ivanvisconti

# Contributing to CSrankings

Thanks for contributing to CSrankings! Please read and indicate you agree with **all** these guidelines to getting your pull request accepted. Note that pull requests may take some time to get merged (please don't contact us for at least three months for updates, unless you are a sponsor - see below).

**If you find CSrankings useful, [please consider becoming a sponsor](https://github.com/sponsors/csrankings).**

**NOTE:** IF YOU DO NOT FOLLOW THE STEPS BELOW, YOUR PULL REQUEST WILL BE SUMMARILY REJECTED.
You must read and check **all** the boxes below by filling them in with an X or your PR will be rejected.

**The Basics**

- [ ] All pull requests and issues must come from non-anonymous accounts. Make sure your GitHub profile contains your full name.

- [ ] Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv").

- [ ] Combine multiple updates to a single institution into a **single PR.**

- [ ] Only submit one pull request per institution.

- [ ] Do not modify any files except `csrankings-[a-z].csv` or (if needed) `country-info.csv` and `old/industry.csv` (see below).

- [ ] Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use the GitHub user interface or a text editor like emacs or NotePad instead.

- [ ] Insert new faculty **in alphabetical order** (not at the end) in the appropriate `csrankings-[a-z].csv` files. **Do not modify `csrankings.csv`, which is auto-generated.**

- [ ] Check to make sure that you have no spaces after commas, or any missing fields.

- [ ] Check to make sure the home page is correct.

- [ ] Make sure the Google Scholar IDs are just the alphanumeric identifier (not a URL or with `&hl=en`).

- [ ] Check to make sure the name corresponds to the DBLP entry (look it up at http://dblp.org).

- [ ] If a faculty member is not in a CS department or similar, include a comment explaining how they meet the inclusion criteria (see below).

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. **Provide justification, pointing to specific home pages
showing how faculty not in a CS department meet the inclusion criteria,
e.g. showing a courtesy appointment in CS.** Faculty must also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put `NOSCHOLARPAGE`.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire CS faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**); include disambiguation suffixes like `0001` as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, *all of them need to be listed*. Do not update `dblp-aliases.csv`.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv` and add *all* of the faculty in the CS department.

**(Advanced) Quick contribution via a shallow clone** 

We recommend that you use the GitHub web user interface to make changes. However, it may be more convenient
to clone the repository for larger-scale changes.

However, a full clone of the CSrankings repository is almost 2GB.  To
contribute a change without creating a full local clone of the
CSrankings repo, you can perform a _shallow clone_.  To do so, follow these
steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)

1. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.

1. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to make another contribution and some time has passed, perform these steps again, creating a fresh fork and shallow clone.

2024-09-25 14:38 UTC, emeryberger requested changes

2024-09-25 14:38 UTC, emeryberger commented on csrankings-i.csv
> +Ivan Visconti,Sapienza University of Rome,https://www.diag.uniroma1.it/users/ivan_visconti,QEairGEAAAAJ
Moved from Computer Science to Computer Engineering - please explain how you continue to meet the specified inclusion criteria.

2024-09-25 14:55 UTC, ivanvisconti commented on csrankings-i.csv
> +Ivan Visconti,Sapienza University of Rome,https://www.diag.uniroma1.it/users/ivan_visconti,QEairGEAAAAJ
I was and still am a professor of computer science (technically speaking "INF/01 - 01/B1" in the Italian classification). Being hired as computer scientist my research and mentoring activity is about comptuer science. There are many other professors in my current department that are listed on csrankings.org. The name of the department does not impact on my status of computer scientist specified in the contract. You can verify it on this website, for simplicity I give you a screenshot of the output of the query: https://cercauniversita.mur.gov.it/php5/docenti/cerca.php
![image](https://github.com/user-attachments/assets/8e6cf547-ee06-42af-a39d-eb850282c1a7)

2024-09-26 00:54 UTC, emeryberger commented on csrankings-i.csv
> +Ivan Visconti,Sapienza University of Rome,https://www.diag.uniroma1.it/users/ivan_visconti,QEairGEAAAAJ
Please confirm that you can (still) solely supervise a PhD student for a PhD in Computer Science.

2024-09-26 06:59 UTC, ivanvisconti commented on csrankings-i.csv
> +Ivan Visconti,Sapienza University of Rome,https://www.diag.uniroma1.it/users/ivan_visconti,QEairGEAAAAJ
AFAIK, by law there is no enforcement for any Italian professor to solely supervise a PhD student for a PhD in Computer Science. I suspect that you mean something more related to actual contents of the reseach topic of the PhD (otherwise all Italian institutions should be removed from csrankings.org, to avoid possible unfair inclusions/exclusions). In this respect, yes, I'm qualified to solely supervise a PhD student for a PhD in Computer Science, meaning that the topic of the research has a primary and largely dominating focus on computer science. FYI, official names of PhD degrees in Italy can be arbitrarely decided by the univeristies, and a student supervised for a PhD in Computer Science (i.e., the topic of the research has a primary and largely dominating focus on computer science) can receive a title of PhD named in various ways (e.g., "Dottore di Ricerca in Cybersecurity", "Dottore di Ricerca in Intelligenza Artificiale", "Dottore di Ricerca in Blockchains e Registri Distribuiti",....).

2024-09-26 16:22 UTC, emeryberger commented on csrankings-i.csv
> +Ivan Visconti,Sapienza University of Rome,https://www.diag.uniroma1.it/users/ivan_visconti,QEairGEAAAAJ
As long as you (and your colleagues) _can_ solely supervise a PhD student with a PhD corresponding to the local equivalent of Computer Science (e.g., _informatica_), you are eligible for inclusion. Thanks.

2024-09-26 16:22 UTC, merged