added 6 faculty for 2018
emeryberger/CSrankings pull request #915
Opened 2018-07-25 11:38 UTC by ravenben

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

2018-07-25 18:02 UTC, emeryberger requested changes

2018-07-25 18:02 UTC, emeryberger commented on csrankings.csv
> +Dong Jin,Illinois Institute of Technology,https://science.iit.edu/people/faculty/kevin-jin,#NAME?
Not sure what happened here but please fix.

2018-07-25 18:02 UTC, emeryberger commented on csrankings.csv
> +Karteek Sreenivasaiah,http://www.iith.ac.in/~karteek,NOSCHOLARPAGE,
Spurious comma at the end...

2018-08-05 15:50 UTC, emeryberger commented
Ping, @ravenben

2018-08-05 21:44 UTC, ravenben commented
sorry, international travel and putting out fires..
getting back to this
—
Ben Y. Zhao http://people.cs.uchicago.edu/~ravenben
Neubauer Professor of Computer Science, University of Chicago
PGP Key ID 0907015B

> On Aug 5, 2018, at 10:50 AM, Emery Berger <notifications@github.com> wrote:
> 
> Ping, @ravenben <https://github.com/ravenben>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/emeryberger/CSrankings/pull/915#issuecomment-410529038>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AcqTVeWVcEtifnIDj8ZOfiylp_8yysLvks5uNxRPgaJpZM4Vf7L_>.
>

2018-08-08 17:16 UTC, emeryberger commented
Safe to close this now?

2018-08-08 17:16 UTC, ravenben commented
yes, please. thanks!
—
Ben Y. Zhao http://people.cs.uchicago.edu/~ravenben
Neubauer Professor of Computer Science, University of Chicago
PGP Key ID 0907015B

> On Aug 8, 2018, at 12:16 PM, Emery Berger <notifications@github.com> wrote:
> 
> Safe to close this now?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/emeryberger/CSrankings/pull/915#issuecomment-411483418>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AcqTVYY_KRpidLNMlh05-Gk7T-bc8RnCks5uOxzdgaJpZM4Vf7L_>.
>

2018-08-08 18:31 UTC, closed without merging