UTD Faculty update
emeryberger/CSrankings pull request #976
Opened 2018-08-21 05:28 UTC by lingming

Dear CSRanking Owner, 

We open a pull request to add a new UTD faculty wei yang, and correct an old UTD faculty's google scholar.

Thanks
Lingming

2018-08-21 16:59 UTC, emeryberger commented on csrankings.csv
> +Wei Yang 0013, University of Texas at Dallas,http://web.engr.illinois.edu/~weiyang3/,CEVHpQUAAAAJ
Please remove the space after the comma and the trailing slash at the end of the web page.

2018-08-21 17:00 UTC, emeryberger requested changes
Please fix this one line.

2018-08-21 17:25 UTC, lingming commented
Sure, it has been updated.
Please let me know if there is any further question.
Thanks a lot!

2018-08-22 01:05 UTC, emeryberger approved these changes

2018-08-22 01:05 UTC, merged